version: '3'
services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_USER: abhi
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb

  owncloud:
    image: owncloud:latest
    restart: always
    depends_on:
      - dbos
    ports:
      - 8081:80
    volumes:
      - owncloud_storage_new:/var/www/html

volumes:
   owncloud_storage_new:
   mysql_storage_new:


